### ISSUE TITLE
Add media queries breakpoints as Neat settings

### ISSUE THREAD

**Issue by Grsmto** [Neverbland/neverbuild#1]
Hey,

As recommended in the Neat documentation (https://github.com/thoughtbot/neat#using-neat) we should define our media queries breakpoints. 

I always have to define some breakpoints when I kickstart a project, and there are pretty much every time the same. 
We could add theses as an example in the `app.scss` file (or create a _grid-settings.scss but it should be the same I think?).

Something like:

```
// Define your breakpoints
$tablet: new-breakpoint(max-width 768px 8);
$mobile: new-breakpoint(max-width 600px 4);
$desktop: new-breakpoint(min-width 1024px);
```

**Comment by vslio** [comment]
We might want to take a look at the link @taha posted recently: http://davidwalsh.name/sass-media-query and get a few ideas.

**Comment by Grsmto** [comment]
As suggested by @maximebonhomme I like the way Foundation Framework deals with media queries: http://foundation.zurb.com/docs/media-queries.html

As an example:

```
$medium-range: (40.063em, 64em); /* 641px, 1024px */
$large-range: (64.063em, 90em); /* 1025px, 1440px */

$medium-up: "#{$screen} and (min-width:#{lower-bound($medium-range)})" !default;
$large-up: "#{$screen} and (min-width:#{lower-bound($large-range)})" !default;
```

**Comment by vslio** [comment]
I like it. Simple enough to keep neverbuild as bloat-free and flexible as possible. I love that it applies on browser zoom as well. @taha had no objections either, so we're all :+1: with it. Wanna take this, @Grsmto?
