### ISSUE TITLE
Use Bitters instead of our own _base.scss

### ISSUE THREAD

**Issue by Grsmto** [Neverbland/neverbuild#14]
As we are already using Bourbon and Neat, maybe we could have a look at Bitters by the same company http://bitters.bourbon.io/

@maximebonhomme used it on a project lately so he could tell us what he thinks about it?

**Comment by vslio** [comment]
Neat and bourbon are just a set of helpers/mixins and don't really add any additional code in the first place. Bitters adds code we probably won't need on most projects.

In my opinion we should just stick to our own slim boilerplate stuff and update that if/when necessary.

**Comment by taha** [comment]
+1

I do however agree with @Grsmto in the sense that we need some base styles there, on top of normalize. Maybe we need some sort of a base "optional" theme if you'd to kickstart a project quickly.
